### ISSUE TITLE
Bug add equipment

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#47]
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/10ae019a-efa0-4a53-9fd1-2565fde0fc5d)

expected: successful
actual: fail

**Comment by NMPhap** [comment]
Đã sửa

**Comment by phuochungus** [comment]
Chừng nào bản patch lên main thì link issue này vô PR đó

**Comment by phuochungus** [comment]
Tested successfully in 11/12
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/2e6b245b-dbf9-4cba-b701-75ddb0a2f91e)
