### ISSUE TITLE
Ở Service Packages, nút "Xóa" không có phản ứng

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#57]
<img width="960" alt="image" src="https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/c6cd4b2f-cb31-4e1c-abd5-f96755914787">

**Comment by ManhHoDinh** [comment]
@phuochungus review lại cái này đi

**Comment by phuochungus** [comment]
@ManhHoDinh 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/2c51bdac-7dd4-49f3-bc13-5534262f63cc)
Không vào được Service

**Comment by ManhHoDinh** [comment]
@phuochungus check lại cái này đi
