### ISSUE TITLE
Ở Employee, Các nút trên thanh Search không thể nhấn

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#61]
<img width="960" alt="image" src="https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/de44ee20-66ab-4b94-866d-1d0bfb5e5a41">

**Comment by phuochungus** [comment]
unable to test, due to

**Comment by Daiduong1593572468** [comment]
![Uploading image.png…]()
đã fix
