### ISSUE TITLE
Ở Sidebar, Nút Floor bị lỗi

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#66]
[screen-recorder-mon-dec-11-2023-19-11-50.webm](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/53456f25-70a4-4086-a257-4bd23ad1dcc0)

**Comment by ManhHoDinh** [comment]
@Daiduong1593572468 Dương đang sửa cái task này

**Comment by ManhHoDinh** [comment]
Thì nhánh m đã được merge vào đâu, nên nó vẫn lỗi bên nhánh main
