### ISSUE TITLE
Functionality: Ở Apartment, Nút Thêm dân cư không nhấn được

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#70]
<img width="960" alt="image" src="https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/976751b4-ff75-4bf0-88f4-be5d6ee07668">

**Comment by ManhHoDinh** [comment]
@vocongbinh sửa cái này

**Comment by phuochungus** [comment]
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/204aed80-07e4-4451-869d-a35fd78ee524)
