### ISSUE TITLE
Ở Apartment, danh sách các Floor bị lặp lại

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#81]
<img width="960" alt="image" src="https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/13a613ce-3a14-44d2-8970-f07d73f4a0cf">

**Comment by NMPhap** [comment]
Entity lập lại ở DATABASE, kiểm tra lại thông tin floor @phuochungus

**Comment by phuochungus** [comment]
@Daiduong1593572468
Thêm unique index (name và building_id) ở table Floor vào code BE, trong trường hợp người dùng thêm Floor bị trùng name trong 1 building, ở BE, trả về 409 conflict

**Comment by phuochungus** [comment]
> @Daiduong1593572468 Thêm unique index (name và building_id) ở table Floor vào code BE, trong trường hợp người dùng thêm Floor bị trùng name trong 1 building, ở BE, trả về 409 conflict https://orkhan.gitbook.io/typeorm/docs/indices#indices-with-multiple-columns

Cách này không giải quyết được vấn đề, lựa tên khác cho floor khi seed database đi là được
