### ISSUE TITLE
Ở Employee, Thông tin ngày sinh không hiển thị theo dd-mm-yyyy

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#91]
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/36501644-293b-42ab-aac2-8d646e40311d)

**Comment by Daiduong1593572468** [comment]
đã fix

**Comment by phuochungus** [comment]
@Daiduong1593572468 
Chưa fix
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/b05240f3-d00a-4f92-848f-c30010977448)

**Comment by Daiduong1593572468** [comment]
ủa 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/100852896/592c9a46-c7d0-481c-97b9-9fdc6b81e4af)
