### ISSUE TITLE
Ở Contract, Ngày hết hạn không thể sửa như trên UI hiển thị

### ISSUE THREAD

**Issue by phuochungus** [phuochungus/HomeLand_Apartment_Management#99]
<img width="960" alt="image" src="https://github.com/phuochungus/HomeLand_Apartment_Management/assets/111514441/9aa443c1-0cce-43a1-a346-24a1d679d703">

**Comment by phuochungus** [comment]
@ManhHoDinh Vẫn chưa sửa được sao lại mention?

**Comment by ManhHoDinh** [comment]
@phuochungus  test lại những issue contract và full luồng service, service package, invoice giúp với
